
version: 2

models:
  - name: dim_date
    description: date dimension created using dbt utility
  
  - name: dim_users
    description: The user dimension table
    columns:
      - name: user_id
        description: Uniquely identify user in greenery
        tests: 
          - unique
          - not_null
      - name: first_name
        description: first name of the user
      - name: last_name
        description: last name of the user
      - name: email
        description : email id of the user
      - name: phone_number
        description : phone number of the user
      - name: created_at_utc
        description : date and time when the user_id was created in the system in UTC
      - name: address_id
        description : address_id of the user 
    
  - name: dim_products
    description: Dimension table to hold product information for greenery
    columns:
      - name: product_id
        description: unqiue identifier for a product
        tests: 
          - unique
          - not_null
      - name: product_name
        description : name of the product
      - name: product_price
        description: price of the product
        test:
          - positive_values
      - name: product_quantity
        description: Available inventory
        test:
          - positive_values
          